#!/bin/bash
echo "=== ESP32 Modbus RTU Server - Kode Statistik ==="
echo ""
echo "📊 TOTAL OVERSIGT:"
echo "---------------------------------------------------"
echo -n "Totalt .cpp filer: "
find src -name "*.cpp" | wc -l
echo -n "Totalt .h filer: "
find include -name "*.h" | wc -l
echo -n "Totalt linjer (.cpp): "
find src -name "*.cpp" -exec cat {} \; | wc -l
echo -n "Totalt linjer (.h): "
find include -name "*.h" -exec cat {} \; | wc -l
echo ""
echo "📁 LINJER PER LAYER:"
echo "---------------------------------------------------"
echo "Layer 0 - Hardware Drivers:"
echo -n "  gpio_driver.cpp: "
wc -l < src/gpio_driver.cpp 2>/dev/null || echo "0"
echo -n "  uart_driver.cpp: "
wc -l < src/uart_driver.cpp 2>/dev/null || echo "0"
echo -n "  pcnt_driver.cpp: "
wc -l < src/pcnt_driver.cpp 2>/dev/null || echo "0"
echo -n "  nvs_driver.cpp: "
wc -l < src/nvs_driver.cpp 2>/dev/null || echo "0"
echo ""
echo "Layer 1 - Modbus Core:"
echo -n "  modbus_frame.cpp: "
wc -l < src/modbus_frame.cpp 2>/dev/null || echo "0"
echo -n "  modbus_parser.cpp: "
wc -l < src/modbus_parser.cpp 2>/dev/null || echo "0"
echo -n "  modbus_serializer.cpp: "
wc -l < src/modbus_serializer.cpp 2>/dev/null || echo "0"
echo ""
echo "Layer 2 - Function Codes:"
echo -n "  modbus_fc_read.cpp: "
wc -l < src/modbus_fc_read.cpp 2>/dev/null || echo "0"
echo -n "  modbus_fc_write.cpp: "
wc -l < src/modbus_fc_write.cpp 2>/dev/null || echo "0"
echo -n "  modbus_fc_dispatch.cpp: "
wc -l < src/modbus_fc_dispatch.cpp 2>/dev/null || echo "0"
echo ""
echo "Layer 3 - Server Runtime:"
echo -n "  modbus_rx.cpp: "
wc -l < src/modbus_rx.cpp 2>/dev/null || echo "0"
echo -n "  modbus_tx.cpp: "
wc -l < src/modbus_tx.cpp 2>/dev/null || echo "0"
echo -n "  modbus_server.cpp: "
wc -l < src/modbus_server.cpp 2>/dev/null || echo "0"
echo ""
echo "Layer 4 - Storage:"
echo -n "  registers.cpp: "
wc -l < src/registers.cpp 2>/dev/null || echo "0"
echo -n "  coils.cpp: "
wc -l < src/coils.cpp 2>/dev/null || echo "0"
echo -n "  gpio_mapping.cpp: "
wc -l < src/gpio_mapping.cpp 2>/dev/null || echo "0"
echo ""
echo "Layer 5 - Counter Engine:"
COUNTER_LINES=$(find src -name "counter_*.cpp" -exec cat {} \; | wc -l)
echo "  Alle counter filer: $COUNTER_LINES linjer"
echo ""
echo "Layer 5 - Timer Engine:"
TIMER_LINES=$(find src -name "timer_*.cpp" -exec cat {} \; | wc -l)
echo "  Alle timer filer: $TIMER_LINES linjer"
echo ""
echo "Layer 5 - ST Logic Engine:"
ST_LINES=$(find src -name "st_*.cpp" -exec cat {} \; | wc -l)
echo "  Alle ST Logic filer: $ST_LINES linjer"
echo ""
echo "Layer 6 - Config System:"
echo -n "  config_struct.cpp: "
wc -l < src/config_struct.cpp 2>/dev/null || echo "0"
echo -n "  config_load.cpp: "
wc -l < src/config_load.cpp 2>/dev/null || echo "0"
echo -n "  config_save.cpp: "
wc -l < src/config_save.cpp 2>/dev/null || echo "0"
echo -n "  config_apply.cpp: "
wc -l < src/config_apply.cpp 2>/dev/null || echo "0"
echo ""
echo "Layer 7 - CLI System:"
CLI_LINES=$(find src -name "cli_*.cpp" -exec cat {} \; | wc -l)
echo "  Alle CLI filer: $CLI_LINES linjer"
echo ""
echo "Layer 8 - System & Network:"
echo -n "  main.cpp: "
wc -l < src/main.cpp 2>/dev/null || echo "0"
echo -n "  heartbeat.cpp: "
wc -l < src/heartbeat.cpp 2>/dev/null || echo "0"
echo -n "  version.cpp: "
wc -l < src/version.cpp 2>/dev/null || echo "0"
echo -n "  network_*.cpp: "
find src -name "network_*.cpp" -exec cat {} \; | wc -l
echo -n "  telnet_*.cpp: "
find src -name "telnet_*.cpp" -exec cat {} \; | wc -l
echo -n "  console_*.cpp: "
find src -name "console_*.cpp" -exec cat {} \; | wc -l
echo -n "  wifi_*.cpp: "
find src -name "wifi_*.cpp" -exec cat {} \; | wc -l
echo ""
echo "NEW v4.0 - Persistence & Watchdog:"
echo -n "  registers_persist.cpp: "
wc -l < src/registers_persist.cpp 2>/dev/null || echo "0"
echo -n "  st_builtin_persist.cpp: "
wc -l < src/st_builtin_persist.cpp 2>/dev/null || echo "0"
echo -n "  watchdog_monitor.cpp: "
wc -l < src/watchdog_monitor.cpp 2>/dev/null || echo "0"
echo ""
echo "📄 DOKUMENTATION:"
echo "---------------------------------------------------"
echo -n "  README.md: "
wc -l < README.md 2>/dev/null || echo "0"
echo -n "  CHANGELOG.md: "
wc -l < CHANGELOG.md 2>/dev/null || echo "0"
echo -n "  CLAUDE.md: "
wc -l < CLAUDE.md 2>/dev/null || echo "0"
echo ""
echo "🎯 HEADER FILER (include/):"
echo "---------------------------------------------------"
echo -n "  constants.h: "
wc -l < include/constants.h 2>/dev/null || echo "0"
echo -n "  types.h: "
wc -l < include/types.h 2>/dev/null || echo "0"
echo -n "  config.h: "
wc -l < include/config.h 2>/dev/null || echo "0"
echo ""
TOTAL_CODE_LINES=$(find src -name "*.cpp" -exec cat {} \; | wc -l)
TOTAL_HEADER_LINES=$(find include -name "*.h" -exec cat {} \; | wc -l)
TOTAL_LINES=$((TOTAL_CODE_LINES + TOTAL_HEADER_LINES))
echo "🏆 GRAND TOTAL:"
echo "---------------------------------------------------"
echo "  Implementation (.cpp): $TOTAL_CODE_LINES linjer"
echo "  Headers (.h): $TOTAL_HEADER_LINES linjer"
echo "  TOTAL KODE: $TOTAL_LINES linjer"
echo ""
