/**
 * @file build_version.h
 * @brief Auto-generated build information
 *
 * DO NOT EDIT MANUALLY - Generated by generate_build_info.py
 */

#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#define BUILD_NUMBER 817
#define BUILD_TIMESTAMP "2025-12-29 10:43:45"
#define BUILD_DATE "20251229"
#define GIT_HASH "0ba7ac7"
#define GIT_BRANCH "main"

#endif // BUILD_VERSION_H
