/**
 * @file build_version.h
 * @brief Auto-generated build information
 *
 * DO NOT EDIT MANUALLY - Generated by generate_build_info.py
 */

#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#define BUILD_NUMBER 138
#define BUILD_TIMESTAMP "2025-11-29 10:45:36"
#define BUILD_DATE "20251129"
#define GIT_HASH "6b3cae9"
#define GIT_BRANCH "main"

#endif // BUILD_VERSION_H
