/**
 * @file build_version.h
 * @brief Auto-generated build information
 *
 * DO NOT EDIT MANUALLY - Generated by generate_build_info.py
 */

#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#define BUILD_NUMBER 1540
#define BUILD_TIMESTAMP "2026-03-24 17:57:50"
#define BUILD_DATE "20260324"
#define GIT_HASH "4782f6a"
#define GIT_BRANCH "main"

#endif // BUILD_VERSION_H
